RPC(
  update,
  INT32_FIELD(msg_len)
  INT32_FIELD(request_id)
  INT32_FIELD(response_to)
  INT32_FIELD(opcode)
  INT32_FIELD(zero)
  CSTRING_FIELD(collection)
  ENUM_FIELD(flags)
  BSON_FIELD(selector)
  BSON_FIELD(update)
)
