#!/bin/sh
# Copyright (c) 2020 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
#
# A helper script to generate source release tarball

GIT_ARCHIVE="$1"
. "`dirname "$0"`/assign_DISTNAME"
git archive --prefix="${DISTNAME}/" --output="${GIT_ARCHIVE}" HEAD
