FROM ubuntu:xenial

#Default repo is peercoin
ARG REPO_NAME=peercoin
#Default branch name develop
ARG BRANCH_NAME=develop

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo
RUN git clone https://github.com/linalouise9/peercoin --branch $BRANCH_NAME --single-branch --depth 1 
RUN cd /peercoin/scripts/windows-crosscompile && ./dependencies.sh 
#xenial
#Missing requirement: libtool
RUN apt install -yqq libtool-bin
RUN cd /peercoin && scripts/windows-crosscompile/compile-peercoin.sh
