#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# add users
adduser --system --group --quiet bitcoin

chaindir="/var/lib/bitcoind"
mkdir -p "$chaindir"
if test ! -f /etc/bitcoin/bitcoin.conf; then
 cp /etc/bitcoin/bitcoin.conf.dist /etc/bitcoin/bitcoin.conf
fi
chown -R bitcoin:bitcoin /etc/bitcoin "$chaindir"

cat <<'EOF'
############################################################
#                                                          #
#  Bitcoin Classic                                         #
#  ____________                                            #
#                                                          #
#  To start bitcoin-classic:                               #
#                                                          #
#      # systemctl start bitcoind                          #
#                                                          #
#  To communicate with bitcoin-classic as a normal user:   #
#                                                          #
#      $ bitcoin-cli help                                  #
#                                                          #
#  Config:        /etc/bitcoin/bitcoin.conf                #
#  Blockchain:    /var/lib/bitcoind                        #
#                                                          #
############################################################
EOF

#DEBHELPER#
