task:
  name: "x86_64 Linux  [GOAL: install]  [bionic]  [Using ./ci/ system]"
  container:
    image: ubuntu:18.04
    cpu: 8
    memory: 8G
  timeout_in: 60m
  env:
    MAKEJOBS: "-j9"
    DANGER_RUN_CI_ON_HOST: "1"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  depends_built_cache:
    folder: "/tmp/cirrus-ci-build/depends/built"
  install_script:
    - apt-get update
    - apt-get -y install git bash ccache
    - ccache --max-size=${CCACHE_SIZE}
  ci_script:
    - ./ci/test_run_all.sh
