base: ubuntu:16.04
language: c++
engine: libFuzzer
environment:
  - CXXFLAGS=-fcoverage-mapping -fno-omit-frame-pointer -fprofile-instr-generate -gline-tables-only -O1
setup:
  - sudo apt-get update
  - sudo apt-get install -y autoconf bsdmainutils clang git libboost-all-dev libboost-program-options-dev libc++1 libc++abi1 libc++abi-dev libc++-dev libclang1 libclang-dev libdb5.3++ libevent-dev libllvm-ocaml-dev libomp5 libomp-dev libprotobuf-dev qtbase5-dev qttools5-dev-tools libqt5svg5-dev libssl-dev libtool llvm llvm-dev llvm-runtime pkg-config protobuf-compiler software-properties-common
  - ./autogen.sh
  - CC=clang CXX=clang++ ./configure --enable-fuzz --with-sanitizers=address,fuzzer,undefined
  - make
  - git clone https://github.com/bitcoin-core/qa-assets
auto_targets:
  find_targets_command: find src/test/fuzz/ -executable -type f ! -name "*.cpp" ! -name "*.h"
  base_corpus_dir: qa-assets/fuzz_seed_corpus/
  memory_limit: none
