#!/bin/bash
echo "Benchmark Results" >output.txt
for j in yasm; do
    echo "5x64 $j:" >>output.txt
    for i in O0 O1 O2 O3; do
        make clean
	./configure --use-5x64 --$j
	echo "OPTLEVEL=$i" >>config.mk
	make bench
	echo "OPTLEVEL=$i" >>output.txt
	(time ./bench) |& grep real >>output.txt
    done
done
    
