#!/usr/bin/env python3
# Copyright (c) 2017-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Test correctness of autocompletion file

Correctness of autocompletion script file for Bash is checked. The test
autogenerates the completion file taking as input the openRPC json
descriptor generated via the getopenrpcinfo bitcoin-cli command.
The autogenerated file is checked against the file
contrib/completions/bitcoin-cli.bash. Test passes if autogenerated
matches actual file, fails otherwise.
It is also possible to execute the test with the --overwrite parameter
to autogenerate and overwrite the current autocompletion file.
"""

from enum import Enum
import re
from os import path

from test_framework.test_framework import BitcoinTestFramework
from test_framework.util import assert_equal


def ind(n: int, s: str) -> str:
    """
    Return indented string
    """
    indent = " " * 4 * n
    return f"{indent}{s}"


class ParamType(Enum):
    NoType = 0
    FilePathType = 1
    DirPathType = 2
    FileOrDirPathType = 3
    BoolType = 4
    EnumType = 5
    StringType = 6
    Number = 7


class Param:

    # Param description regexpr to match file and/or directory path types
    # match "file" as whole word, case insensitive
    file_pattern = r"(?i)\bfile\b"
    # match "directory" or "path" as case insensitive
    directory_pattern = r"(?i)\b(?:directory|path)\b"
    # match ("directory" or "path") and "file" case insensitive
    directory_or_file_pattern = (
        r"(?i)^(?=.*\b(?:directory|path)\b)"
        r"(?=.*\bfile\b).*"
    )

    def __init__(self, param_json):
        self.name = param_json["name"]
        self._type = Param.infer_param_type(param_json)

    @property
    def param_type(self) -> ParamType:
        return self._type

    @staticmethod
    def infer_param_type(param_json):
        schema_json = param_json.get("schema", "")
        type_val = schema_json.get("type", "")
        if type_val == "string":
            description = param_json.get("description", "")
            # guess if it is directory and/or file path from description
            if re.search(Param.directory_or_file_pattern, description):
                return ParamType.FileOrDirPathType
            if re.search(Param.file_pattern, description):
                return ParamType.FilePathType
            if re.search(Param.directory_pattern, description):
                return ParamType.DirPathType
            return ParamType.StringType
        if type_val == "number":
            return ParamType.Number
        if type_val == "boolean":
            return ParamType.BoolType
        # todo: enum type not yet supported
        return ParamType.NoType


class BashCompletion:
    # Skip RPC commands shown below
    skip_categories = ("zmq")
    # match bitcoin-cli arguments from "bitcoin-cli -help" output
    bcli_help_arguments_pattern = r"^  (-[^=\s]+=?)"

    bash_header = [
        "# bash programmable completion for bitcoin-cli(1)",
        "# Copyright (c) 2012-present The Bitcoin Core developers",
        "# Do NOT modify this file. This file is autogenerated by the",
        "# functional test tool_rpc_autocompletion and can be overwritten by",
        "#",
        "# python build/test/functional/tool_rpc_autocompletion.py"
        " --overwrite",
        "#",
        "# Distributed under the MIT software license, see the accompanying",
        "# file COPYING or http://www.opensource.org/licenses/mit-license.php."
    ]

    bash_named_helper = [
        "_named() {",
        ind(1, "# check if -named option has been requested"),
        ind(1, "for opt in ${COMP_LINE}; do"),
        ind(2, "[[ \"$opt\" == \"-named\" ]] && return 0"),
        ind(1, "done"),
        ind(1, "return 1"),
        "}"
    ]

    bash_method_helper = [
        "_method() {",
        ind(1, "# return rpc method (first non option argument)"),
        ind(1, "local arg"),
        ind(1, "for arg in \"${words[@]:1}\"; do"),
        ind(2, "[[ $arg != -* ]] && {"),
        ind(3, "echo \"$arg\""),
        ind(3, "return 0"),
        ind(2, "}"),
        ind(1, "done"),
        ind(1, "return 1"),
        "}"
    ]

    bash_bitcoin_cli = [
        "_bitcoin_cli() {",
        ind(1, "# main handler"),
        ind(1, "local cur prev words=() cword"),
        ind(1, "COMPREPLY=()"),
        ind(1, "_get_comp_words_by_ref -n = cur prev words cword"),
        ind(1, "local method"),
        ind(1, "method=$(_method)"),
        "",
        ind(1, "# Named mode: typing a global option (starts with -)"),
        ind(1, "if _named && [[ \"$cur\" == -* ]]; then"),
        ind(2, "COMPREPLY=( $( compgen -W \"${helpopts[*]}\" -- \"$cur\" ) )"),
        ind(2, "return"),
        ind(1, "fi"),
        "",
        ind(1, "# Named mode: typing (or completing) the method name"),
        ind(1, "if _named && [[ \"$cur\" == \"$method\" ]]; then"),
        ind(2, "COMPREPLY=( $( compgen -W \"${helpopts[*]} ${methods[*]}\" -- \"$cur\" ) )"),
        ind(2, "return"),
        ind(1, "fi"),
        "",
        ind(1, "# Named mode: typing named parameters for the method"),
        ind(1, "if _named; then"),
        ind(2, "_bitcoin_cli_named"),
        ind(2, "[[ $COMPREPLY == *= ]] && compopt -o nospace"),
        ind(2, "return"),
        ind(1, "fi"),
        "",
        ind(1, "# Positional mode: delegate to positional handler"),
        ind(1, "_bitcoin_cli_positional"),
        ind(1, "[[ ${#COMPREPLY[@]} -gt 0 || (-n \"$method\" && \"$method\" != \"$cur\") ]] && return"),
        "",
        ind(1, "case \"$cur\" in"),
        ind(2, "-conf=*)"),
        ind(3, "cur=\"${cur#*=}\""),
        ind(3, "_filedir"),
        ind(3, "return 0"),
        ind(3, ";;"),
        ind(2, "-datadir=*)"),
        ind(3, "cur=\"${cur#*=}\""),
        ind(3, "_filedir -d"),
        ind(3, "return 0"),
        ind(3, ";;"),
        ind(2, "-*=*) # prevent nonsense completions"),
        ind(3, "return 0"),
        ind(3, ";;"),
        ind(2, "*)"),
        ind(3, "COMPREPLY=( $( compgen -W \"${helpopts[*]} ${methods[*]}\" -- \"$cur\" ) )"),
        ind(3, "# Prevent space if an argument is desired"),
        ind(3, "if [[ $COMPREPLY == *= ]]; then"),
        ind(4, "compopt -o nospace"),
        ind(3, "fi"),
        ind(3, "return 0"),
        ind(3, ";;"),
        ind(1, "esac"),
        "} &&"
    ]

    def __init__(self, json_openrpc, bcli_help):
        # Filter out methods belonging to skip_categories
        self.json_methods = [
            method
            for method in json_openrpc.get("methods", [])
            if method.get("x-bitcoin-category") not in self.skip_categories
        ]
        self.methods_string = [method.get("name", "") for method in self.json_methods]
        self.helpopts_string = re.findall(
            self.bcli_help_arguments_pattern,
            bcli_help,
            re.MULTILINE,
            )

    def get_bash(self) -> list[str]:
        return [
            *self.bash_header,
            "",
            f"methods=({' '.join(self.methods_string)})",
            f"helpopts=({' '.join(self.helpopts_string)})",
            "",
            *self.bash_named_helper,
            "",
            *self.bash_method_helper,
            "",
            *self.get_bitcoin_cli_positional(),
            "",
            *self.get_bitcoin_cli_named(),
            "",
            *self.bash_bitcoin_cli,
            "complete -F _bitcoin_cli bitcoin-cli"
        ]

    @staticmethod
    def get_bitcoin_cli_named_non_string_param(indent: int, param: Param):
        outlines = []
        outlines.append(ind(indent, param.name + "=*)"))
        if param.param_type == ParamType.FilePathType:
            outlines.append(ind((indent+1), "cur=\"${cur#*=}\""))
            outlines.append(ind((indent+1), "_filedir"))
        elif param.param_type == ParamType.DirPathType:
            outlines.append(ind((indent+1), "cur=\"${cur#*=}\""))
            outlines.append(ind((indent+1), "_filedir -d"))
        elif param.param_type == ParamType.FileOrDirPathType:
            outlines.append(ind((indent+1), "cur=\"${cur#*=}\""))
            outlines.append(ind((indent+1), "_filedir"))
        elif param.param_type == ParamType.BoolType:
            outlines.append(ind((indent+1), "COMPREPLY=( $( compgen -W \"true false\" -- \"$cur\" ) )"))
        else:
            # todo: enum type handling
            pass
        outlines.append((indent+1)*"\t" + "return 0")
        outlines.append((indent+1)*"\t" + ";;")
        return outlines

    @staticmethod
    def get_bitcoin_cli_named_method_params(indent: int, method_json: dict) -> list[str]:
        """
        Generate formatted output lines for arguments related to a named
        bitcoin-cli method
        """
        has_non_string_type = False
        outlines = []
        param_names = []
        sub_indent = indent
        for param_json in method_json.get("params", []):
            param = Param(param_json)
            param_names.append(f"{param.name}=")
            if param.param_type in (
                ParamType.StringType,
                ParamType.NoType,
                ParamType.Number
                ):
                continue
            if not has_non_string_type:
                outlines.append(ind(sub_indent, 'case "$cur" in'))
                has_non_string_type = True
            outlines.extend(BashCompletion.get_bitcoin_cli_named_non_string_param(indent+1, param))
        if has_non_string_type:
            sub_indent += 1
            outlines.append(ind(sub_indent, "*)"))
        if param_names:
            sub_indent += 1
            outlines.append(ind(sub_indent, "COMPREPLY=( $( compgen -W \"" + " ".join(param_names) + "\" -- \"$cur\" ) )"))
        outlines.extend(
            [
                ind(sub_indent, "return 0"),
                ind(sub_indent, ";;")
            ]
        )
        if has_non_string_type:
            outlines.extend(
                [
                    ind(indent, "esac"),
                    ind(indent, ";;")
                ]
            )
        return outlines

    @staticmethod
    def get_bitcoin_cli_named_method(indent: int, method_json: dict) -> list[str]:
        """
        Generate formatted output lines for a bitcoin-cli named method.
        """
        params = method_json.get("params", [])
        if not params:
            return []
        method_name = method_json.get("name", "")
        return [
            ind(indent, f"{method_name})"),
            *BashCompletion.get_bitcoin_cli_named_method_params(indent+1, method_json)
        ]

    def get_bitcoin_cli_named(self):
        """
        Generate formatted output for bitcoin_cli_named() helper function.
        """
        outlines = [
            "_bitcoin_cli_named() {",
            ind(1, "case \"$(_method)\" in")
            ]
        for method_json in self.json_methods:
            outlines.extend(BashCompletion.get_bitcoin_cli_named_method(2, method_json))
        outlines.extend(
            [
                ind(2, "*)"),
                ind(3, "# No method found, skip"),
                ind(3, "return 0"),
                ind(3, ";;"),
                ind(1, "esac"),
                "}"
            ]
        )
        return outlines

    def get_bitcoin_cli_positional_n(self, indent: int, n: int) -> list[str]:
        """
        Return completion hints for parameter at n-th position.
        """
        def generate_code(indent: int, methods: list[str], helper: str) -> list[str]:
            if methods:
                return [
                    ind(indent+2, f"{'|'.join(methods)})"),
                    ind(indent+3, helper),
                    ind(indent+3, "return 0"),
                    ind(indent+3, ";;")
                ]
            return []
        found = False
        if n == 0:
            outlines = [ind(indent, "case $prev in")]
        else:
            outlines = [
                ind(indent, f"if ((cword > {n+1})); then"),
                ind(indent+1, f"case ${{words[cword-{n+1}]}} in")
                ]
        methods_file = []
        methods_dir = []
        methods_boolean = []
        for method in self.json_methods:
            params = method.get("params", [])
            if n >= len(params):
                continue
            param = Param(params[n])
            if param.param_type == ParamType.BoolType:
                methods_boolean.append(method.get("name", ""))
            elif param.param_type in (
                ParamType.FileOrDirPathType,
                ParamType.FilePathType
            ):
                methods_file.append(method.get("name", ""))
            elif param.param_type == ParamType.DirPathType:
                methods_dir.append(method.get("name", ""))
        if methods_boolean:
            helper = "COMPREPLY=( $( compgen -W \"true false\" -- \"$cur\" ) )"
            outlines.extend(generate_code(indent, methods_boolean, helper))
            found = True
        if methods_file:
            helper = "_filedir"
            outlines.extend(generate_code(indent, methods_file, helper))
            found = True
        if methods_dir:
            helper = "_filedir -d"
            outlines.extend(generate_code(indent, methods_dir, helper))
            found = True
        if found and n == 0:
            outlines.append(ind(indent, "esac"))
        elif found:
            outlines.extend(
                [
                    ind(indent+1, "esac"),
                    ind(indent, "fi")
                ]
            )
        else:
            return []
        return outlines

    def get_bitcoin_cli_positional(self) -> list[str]:
        """
        Generate formatted output for bitcoin_cli_positional()
        helper function.
        """
        max_params = max(
            (len(method.get("params", [])) for method in self.json_methods), default=0
        )
        return [
            "_bitcoin_cli_positional() {",
            *(line for n in reversed(range(max_params)) for line in self.get_bitcoin_cli_positional_n(1, n)),
            ind(1, "return 1"),
            "}"
        ]


class RPCAutocompletionTest(BitcoinTestFramework):

    def set_test_params(self):
        self.setup_clean_chain = True
        self.num_nodes = 1
        self.uses_wallet = True # enable wallet related commands

    def skip_test_if_missing_module(self):
        self.skip_if_no_cli()
        self.skip_if_no_wallet()

    def add_options(self, parser):
        parser.add_argument(
            '--overwrite',
            default=False,
            action='store_true',
            dest='overwrite',
            help="Overwrite the current completion file(s)"
            )

    def setup_network(self):
        self.setup_nodes()

    def read_bash_file(self):
        try:
            with open(self.bash_completion_file_path, 'r', encoding='utf-8') as bash_file:
                return bash_file.read()
        except Exception as e:
            raise AssertionError(
                f"Unable to read Bash completion file: {e} "
                f"File is expected in {self.bash_completion_file_path}"
            )

    def overwrite_bash_file(self):
        try:
            with open(self.bash_completion_file_path, 'w', encoding='utf-8') as bash_file:
                bash_file.write(self.generated_bash_file)
        except Exception as e:
            raise AssertionError(
                f"Unable to overwrite bash completion file: {e} "
            )

    def run_test(self):
        """Main test logic"""
        src_dir = self.config["environment"]["SRCDIR"]

        # Generate autocompletion file content for Bash and check if it matches
        # with the current autocompletion file stored in the expected folder
        self.bash_completion_file_path = path.join(
            src_dir,
            'contrib',
            'completions',
            'bash',
            'bitcoin-cli.bash'
            )
        self.log.info("Calling \"bitcoin-cli -help\" output and parse bitcoin-cli options")
        bcli_help = self.nodes[0].cli('-help').send_cli()
        self.log.info("Calling \"bitcoin-cli getopenrpcinfo\" and parse argument data")
        openrpcinfo = self.nodes[0].getopenrpcinfo()
        self.log.info("Generating Bash completion file content")
        bash_handler = BashCompletion(openrpcinfo, bcli_help)
        self.generated_bash_file = "\n".join(bash_handler.get_bash()) + "\n"

        # Overwrite bash completion file if --overwrite requested
        if self.options.overwrite:
            self.log.info("Overwriting Bash completion file with autogenerated one")
            self.overwrite_bash_file()

        # Existing Bash completion file
        current_bash_file = self.read_bash_file()
        self.log.info("Checking stored file and generated one have same content")
        self.log.info("If not, consider re-executing this test with --overwrite option")
        assert_equal(self.generated_bash_file, current_bash_file)


if __name__ == '__main__':
    RPCAutocompletionTest(__file__).main()
