name: Issue or feature request related to the GUI
description: Any report, issue or feature request related to the GUI
labels: [GUI]
body:
- type: checkboxes
  id: acknowledgement
  attributes:
    label: Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo
    description: https://github.com/syscoin-core/gui/issues/
    options:
      - label: I still think this issue should be opened here
        required: true
- type: textarea
  id: gui-request
  attributes:
    label: Report
  validations:
    required: true
