.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. liberta_qt test_liberta_qt
clean: FORCE
	$(MAKE) -C .. liberta_qt_clean test_liberta_qt_clean
check: FORCE
	$(MAKE) -C .. test_liberta_qt_check
liberta-qt liberta-qt.exe: FORCE
	 $(MAKE) -C .. liberta_qt
