from typing import Any, Optional

REFERENCE_FILENAME: str

class AuthServiceProxyWrapper:
    auth_service_proxy_instance: Any = ...
    coverage_logfile: Any = ...
    def __init__(self, auth_service_proxy_instance: Any, coverage_logfile: Optional[Any] = ...) -> None: ...
    def __getattr__(self, name: Any): ...
    def __call__(self, *args: Any, **kwargs: Any): ...
    def __truediv__(self, relative_uri: Any): ...
    def get_request(self, *args: Any, **kwargs: Any): ...

def get_filename(dirname: Any, n_node: Any): ...
def write_all_rpc_commands(dirname: Any, node: Any): ...
