from typing import Any

INPUT_CHARSET: str
CHECKSUM_CHARSET: str
GENERATOR: Any

def descsum_polymod(symbols: Any): ...
def descsum_expand(s: Any): ...
def descsum_create(s: Any): ...
def descsum_check(s: Any, require: bool = ...): ...
def drop_origins(s: Any): ...
