from typing import Any

STATE_LISTEN: str

def get_socket_inodes(pid: Any): ...
def netstat(typ: str = ...): ...
def get_bind_addrs(pid: Any): ...
def all_interfaces(): ...
def addr_to_hex(addr: Any): ...
def test_ipv6_local(): ...
