from typing import Any

logger: Any

class Command:
    CONNECT: int = ...

class AddressType:
    IPV4: int = ...
    DOMAINNAME: int = ...
    IPV6: int = ...

def recvall(s: Any, n: Any): ...

class Socks5Configuration:
    addr: Any = ...
    af: Any = ...
    unauth: bool = ...
    auth: bool = ...
    def __init__(self) -> None: ...

class Socks5Command:
    cmd: Any = ...
    atyp: Any = ...
    addr: Any = ...
    port: Any = ...
    username: Any = ...
    password: Any = ...
    def __init__(self, cmd: Any, atyp: Any, addr: Any, port: Any, username: Any, password: Any) -> None: ...

class Socks5Connection:
    serv: Any = ...
    conn: Any = ...
    def __init__(self, serv: Any, conn: Any) -> None: ...
    def handle(self) -> None: ...

class Socks5Server:
    conf: Any = ...
    s: Any = ...
    running: bool = ...
    thread: Any = ...
    queue: Any = ...
    def __init__(self, conf: Any) -> None: ...
    def run(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
