# Copyright (c) 2019-2020 Xenios SEZC
# https://www.veriblock.org
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
#
#all:
#	$(MAKE) -C .. vbk_integration_test
#clean:
#	$(MAKE) -C .. vbk_integration_test_clean
#inttest:
#	$(MAKE) -C .. vbk_integration_test_check
