#!/usr/bin/env ruby

require File.expand_path('../boot', __FILE__)

if ARGV.size < 1 or ARGV.size > 2
  puts "usage: $0 <image name> [<n>]"
  puts "Will display the log of the last (or nth last) container that used image <image name>"
  puts "Example: $0 peercoinnet/a"
  exit 1
end

name = ARGV[0]
if ARGV.size > 1
  n = ARGV[1].to_i
else
  n = 0
end
raise if n < 0

containers=Docker::Container.all(all: true)
containers = containers.select { |container| container.info["Image"].split(':').first == name }
if n >= containers.size
  raise "No container found"
end
container = containers[n]
id = container.id

exec "docker attach #{id}"
