# Copyright (c) 2023 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

function(get_all_executables output)
  set(${output})
  if(BUILD_DAEMON)
    list(APPEND ${output} "$<TARGET_FILE:bitcoind>")
  endif()
  if(BUILD_CLI)
    list(APPEND ${output} "$<TARGET_FILE:bitcoin-cli>")
  endif()
  if(BUILD_TX)
    list(APPEND ${output} "$<TARGET_FILE:bitcoin-tx>")
  endif()
  if(BUILD_UTIL)
    list(APPEND ${output} "$<TARGET_FILE:bitcoin-util>")
  endif()
  if(BUILD_UTIL_CHAINSTATE)
    list(APPEND ${output} "$<TARGET_FILE:bitcoin-chainstate>")
  endif()
  if(BUILD_WALLET_TOOL)
    list(APPEND ${output} "$<TARGET_FILE:bitcoin-wallet>")
  endif()
  if(BUILD_TESTS)
    list(APPEND ${output} "$<TARGET_FILE:test_bitcoin>")
  endif()
  if(BUILD_BENCH)
    list(APPEND ${output} "$<TARGET_FILE:bench_bitcoin>")
  endif()
  set(${output} ${${output}} PARENT_SCOPE)
endfunction()
