#!/usr/bin/env just

Justfile:
	@echo "running just"

image_name := 'bitcoin-builder'

export BDB_PREFIX := `pwd` + '/db4'

build-image:
	IMAGE_NAME={{image_name}} ./build-docker-image.sh

build: setup configure rebuild

build-all: build-image build

setup *args='':
	IMAGE_NAME={{image_name}} ./docker-env ./contrib/install_db4.sh $(pwd) "$@"

@configure *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	IMAGE_NAME={{image_name}} ./docker-env ./autogen.sh
	IMAGE_NAME={{image_name}} ./docker-env ./configure {{args}} BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"

rebuild:
	IMAGE_NAME={{image_name}} ./docker-env make
