.TH DASH-CLI "1" "June 2016" "dash-cli 0.12"
.SH NAME
dash-cli \- a remote procedure call client for Dash Core. 
.SH SYNOPSIS
dash-cli [options] <command> [params] \- Send command to Dash Core. 
.TP
dash-cli [options] help \- Asks Dash Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the dash-cli program. dash-cli is an RPC client used to send commands to Dash Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBdashd\fP, \fBdash.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
