.TH DASHD "1" "June 2016" "dashd 0.12"
.SH NAME
dashd \- peer-to-peer network based digital currency
.SH SYNOPSIS
dashd [options] <command> [params]
.TP
dashd [options] help <command> \- Get help for a command
.SH DESCRIPTION
This  manual page documents the dashd program. Dash is an experimental new digital currency that enables anonymous, instant payments to anyone, anywhere in the world. Dash uses peer-to-peer technology to operate with no central authority: managing transactions and issuing money are carried out collectively by the network. Dash Core is the name of the open source software which enables the use of this currency.

.SH OPTIONS
.TP
\-?
List of possible options.
.SH COMMANDS
.TP
\fBhelp\fR
List commands.

.TP
\fBhelp 'command'\fR
Get help for a command.

.SH "SEE ALSO"
dash.conf(5)
.SH AUTHOR
This manual page was written by Micah Anderson <micah@debian.org> for the Debian system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.

