name: Benchmark
on:
  pull_request:
    branches:
      - master

jobs:
  benchmark:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 600
    env:
      ORIGINAL_DATADIR: /data/pruned-840k
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run experiment
        run: |
          nix develop --command python3 bench.py experiment run \
            bench/experiments/pr.toml \
            --datadir $ORIGINAL_DATADIR \
            --tmp-dir ${{ runner.temp }}/datadirs \
            --binaries-dir ${{ runner.temp }}/binaries \
            --output-dir ${{ runner.temp }}/experiment-output \
            --skip-existing

      - name: Upload experiment output
        uses: actions/upload-artifact@v7
        with:
          name: experiment-output
          path: ${{ runner.temp }}/experiment-output/

      - name: Write context metadata
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          mkdir -p ${{ runner.temp }}/contexts
          echo "$GITHUB_CONTEXT" | nix develop --command jq "del(.token)" > ${{ runner.temp }}/contexts/github.json
          echo "$RUNNER_CONTEXT" > ${{ runner.temp }}/contexts/runner.json

      - name: Upload context metadata
        uses: actions/upload-artifact@v7
        with:
          name: run-metadata
          path: ${{ runner.temp }}/contexts/
