# Copyright (c) 2023-present The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit.

name: Silent Merge Conflict Check
on:
  pull_request:
    types: [labeled]

env:
  CIRRUS_CACHE_HOST: http://127.0.0.1:12321/ # When using Cirrus Runners this host can be used by the docker `gha` build cache type.
  REPO_USE_CIRRUS_RUNNERS: 'bitcoin/bitcoin' # Use cirrus runners and cache for this repo, instead of falling back to the slow GHA runners

defaults:
  run:
    # Enforce fail-fast behavior for all platforms.
    # See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  runners:
    name: 'Determine runners'
    runs-on: ubuntu-24.04
    outputs:
      use-cirrus-runners: ${{ steps.runners.outputs.use-cirrus-runners }}
    steps:
      - id: runners
        run: |
          if [[ "${REPO_USE_CIRRUS_RUNNERS}" == "${{ github.repository }}" ]]; then
            echo "use-cirrus-runners=true" >> "$GITHUB_OUTPUT"
            echo "::notice title=Runner Selection::Using Cirrus Runners"
          else
            echo "use-cirrus-runners=false" >> "$GITHUB_OUTPUT"
            echo "::notice title=Runner Selection::Using GitHub-hosted runners"
          fi

  previous-releases:
    name: 'Previous releases, depends DEBUG'
    if: contains(github.event.label.name, 'PeriodicMergeCICheck')
    needs: runners
    runs-on: ${{ needs.runners.outputs.use-cirrus-runners == 'true' && 'ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-md' || 'ubuntu-24.04' }}

    env:
      FILE_ENV: './ci/test/00_setup_env_native_previous_releases.sh'
      DANGER_CI_ON_HOST_FOLDERS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure environment
        uses: ./.github/actions/configure-environment

      - name: Restore caches
        id: restore-cache
        uses: ./.github/actions/restore-caches

      - name: Configure Docker
        uses: ./.github/actions/configure-docker
        with:
          use-cirrus: ${{ needs.runners.outputs.use-cirrus-runners }}

      - name: CI script
        run: ./ci/test_run_all.sh

      - name: Save caches
        uses: ./.github/actions/save-caches
        with:
          depends-sources-cache-hit: ${{ steps.restore-cache.depends-sources-cache-hit }}
          depends-built-cache-hit: ${{ steps.restore-cache.depends-built-cache-hit }}

  lint:
    name: 'Lint'
    if: contains(github.event.label.name, 'PeriodicMergeCICheck')
    needs: runners
    runs-on: ${{ needs.runners.outputs.use-cirrus-runners == 'true' && 'ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-sm' || 'ubuntu-24.04' }}
    timeout-minutes: 20
    env:
      CONTAINER_NAME: "bitcoin-linter"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Docker
        uses: ./.github/actions/configure-docker
        with:
          use-cirrus: ${{ needs.runners.outputs.use-cirrus-runners }}

      - name: CI script
        run: |
          set -o xtrace
          docker buildx build -t "$CONTAINER_NAME" $DOCKER_BUILD_CACHE_ARG --file "./ci/lint_imagefile" .
          CIRRUS_PR_FLAG=""
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CIRRUS_PR_FLAG="-e CIRRUS_PR=1"
          fi
          docker run --rm $CIRRUS_PR_FLAG -v "$(pwd)":/bitcoin "$CONTAINER_NAME"
