#!/bin/sh

set -e

arch=$1
prog=$2

cd /qemu/init
echo "#!/bin/sh\n/prog --color=never" > run_prog.sh
chmod +x run_prog.sh
cp -f $2 prog
find . | cpio --create --format='newc' --quiet | gzip > ../initrd.gz
cd ..

timeout 30s qemu-system-$arch \
  -m 1024 \
  -nographic \
  -kernel kernel \
  -initrd initrd.gz \
  -append init=/run_prog.sh > output || true

# remove kernel messages
tr -d '\r' < output | egrep -v '^\['

egrep "(PASSED)|(test result: ok)" output > /dev/null
